### PR TITLE
Upstream changes from Servo

### PR DESCRIPTION
**Pull request by Manishearth**
This contains changes which add flake8 linting to the CI, and a fix for #100.

The multiple build thing seems to work fine for us with appveyor.

Let me know if I should exclude something! I'd like servo/homu and homu/homu to be near-identical, with servo being a bit more liberal in accepting fixes which get eventually upstreamed to homu after style decisions and testing is done.

r? @barosl

### CODE REVIEW

**Comment by Manishearth** [comment]
cc @frewsxcv @larsbergstrom

**Comment by sigmavirus24** [comment]
This is a giant change in a single pull request. Also, nitpicking: Isn't barosl/homu upstream and servo a downstream fork? ;)

**Comment by Manishearth** [comment]
@sigmavirus24 It isn't, there are only two changes in this PR (the rest are merge pull requests).

Yes, barosl/homu is upstream, hence "upstreaming". I'm using it as a verb.

**Comment by Manishearth** [comment]
Superseded by #133

**Comment by frewsxcv** [comment]
Superseded by https://github.com/barosl/homu/issues/134

**Pull request closed without merging**
