### PR TITLE
Add some logging about missing results on startup.

### PR DESCRIPTION
**Pull request by brson**
This logging tells me what things homu is still looking for
so I can restart them.

### CODE REVIEW

**Comment by barosl** [comment]
In general, you can find the pull request Homu is waiting for by looking at the PENDING state in the queue. Is there a particular reason why this information is also needed in the command line interface? As the things displayed on the command line interface is only shown by the ssh'ing user, I would like to limit its usage to purely debug purposes.

**Comment by brson** [comment]
Closing this since it's old and irrelevant to my current work. I am finding it infuriating that homu doesn't log what it's thinking. Every once in a while homu seems to lose messages from buildbot and becomes unable to recover, and I have *no idea* what homu is thinking about the state of the world - what PR is it waiting on, how do i get it to move on?

**Comment by brson** [comment]
Sorry for the harsh critique. I was debugging a stuck homu at the time.

**Comment by barosl** [comment]
Sorry for the inconvenience, @brson. It must have been an irritating experience.

I find it worrisome that the Homu queue is continuously being stuck. IMO in most cases posting `@bors retry` on the `PENDING` PRs would be sufficient, because the losses of the "done" messages from GitHub and Buildbot make Homu wait for them indefinitely. So it should be retried. (Or you should let GitHub and Buildbot send the packets again, but it would be more or less harder.) But I guess the problem the Rust project is having is something different? How did you resolve the problem this time?

More logging will be definitely useful. In fact, some logging feature had been added by @huonw, but it seems to be not enabled by default. I will tackle this problem soon.

Again, sorry for the annoyance! I think I was too lazy on this matter. If you experience another problem again, please don't hesitate to bug me. I'll try to be there.

**Comment by brson** [comment]
@barosl I have never `@bors retry` in this situation because i don't want to go through another multi-hour build when the build *did* complete.

The problem we had yesterday we think turned out to be a bug in our *buildbot* deployment: homu was requesting builds but buildbot wasn't doing them because of a misconfiguration. So ... false alarm. Very sorry :bow:

**Comment by barosl** [comment]
@brson Ah, I see! That's fortunate for *Homu's side*. :stuck_out_tongue_closed_eyes:

I had an idea for the problem you're describing. Homu is now capable of reading the build states from the GitHub statuses. It was primarily done to support Travis in more general fashion (previously Travis -> Homu, but now Travis -> GitHub -> Homu), but I think it could be also applicable to our current Buildbot deployment.

We may add a Buildbot configuration to post its build results to GitHub directly, and Homu just retrieves the statuses from GitHub. In this way Buildbot will look more "natural" in the GitHub interface, because everyone can see what's going on in Buildbot from the PR page. Also, it would contribute to separation of concerns, as Buildbot only deals with GitHub, and Homu only looks at GitHub. Plus it would help debugging issues like this.

**Comment by brson** [comment]
@barosl ah, that sounds like a neat simplification, yeah!

**Pull request closed without merging**
